# Generated by Django 4.2.4 on 2023-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CropMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=20)),
                ("supplier", models.CharField(blank=True, max_length=20)),
                ("origin", models.CharField(blank=True, max_length=20)),
                ("crop_date", models.DateField()),
                ("crop_supply", models.IntegerField(null=True)),
                ("crop_price", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Jeju",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PredictionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=20)),
                ("supplier", models.CharField(blank=True, max_length=20)),
                ("origin", models.CharField(blank=True, max_length=20)),
                ("crop_date", models.DateField()),
                ("crop_price", models.FloatField()),
                ("ai_model", models.CharField(max_length=30)),
            ],
        ),
    ]
