# Generated by Django 4.2.4 on 2023-11-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppOfJeju", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=20)),
                ("supplier", models.CharField(blank=True, max_length=20)),
                ("crop_date", models.DateField()),
                ("crop_supply", models.IntegerField(null=True)),
                ("crop_price", models.IntegerField(null=True)),
            ],
        ),
    ]
