# Generated by Django 4.2.4 on 2023-11-27 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppOfJeju", "0003_retailpredictiondata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailpredictiondata",
            name="supplier",
        ),
    ]
