# Generated by Django 4.2.4 on 2023-11-20 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppOfJeju", "0004_predictiondata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictiondata",
            name="crop_supply",
        ),
    ]
